### GET All Todo
GET http://localhost:8080/restapi/TodoDtos

### GET Todo with id of 2
GET http://localhost:8080/restapi/TodoDtos/2

### CREATE new TodoItem
POST http://localhost:8080/restapi/TodoDtos
Content-Type: application/json

{
  "name": "Finish DTO Demo",
  "complete": false
}

### Update TodoItem with id of 4
PUT http://localhost:8080/restapi/TodoDtos/4
Content-Type: application/json

{
  "id": 4,
  "name": "Commit and push DTO example",
  "complete": true,
  "version": 0
}

### DELETE TodoItem with an id of 4
DELETE http://localhost:8080/restapi/TodoDtos/4









